import { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { NeoCard, NeoInput, NeoButton, NeoToggle } from '../neo';
import { useAIAgent } from '../../hooks/useAIAgent';
import { useAgentsContext } from '../../contexts/AgentsContext';

interface AgentSettingsProps {
  onClose?: () => void;
}

export const AgentSettings = ({ onClose }: AgentSettingsProps) => {
  const { createAgent } = useAIAgent();
  const { refresh } = useAgentsContext();
  const [loading, setLoading] = useState(false);

  // User cuma input nama, ID kita generate otomatis biar anti-ribet
  const [agentName, setAgentName] = useState('');
  const [settings, setSettings] = useState({
    maxBudgetPerTicket: 0.1,
    totalBudget: 1.0,
    autoPurchaseEnabled: true,
    autoPurchaseThreshold: 100, // 100% dari max budget
  });

  const handleSave = useCallback(async () => {
    if (!agentName.trim()) {
      alert('KASIH NAMA DULU BOT-NYA, CU! MASA ANONIM?');
      return;
    }

    setLoading(true);
    try {
      /**
       * //AUTO-GENERATED ID
       * Kita pake format AGENT-TIMESTAMP biar unik di level blockchain
       */
      const autoGeneratedId = `AGENT-${Date.now()}`;

      console.log("🚀 Birthing new agent:", { name: agentName, id: autoGeneratedId });

      // Tembak hook useAIAgent (pastiin hook lo udah support urutan parameter baru)
      await createAgent({
        agentId: autoGeneratedId,
        name: agentName,
        maxBudgetPerTicket: settings.maxBudgetPerTicket * 1e9, // SOL to Lamports
        totalBudget: settings.totalBudget * 1e9,
        autoPurchaseEnabled: settings.autoPurchaseEnabled,
        autoPurchaseThreshold: settings.autoPurchaseThreshold,
        maxTicketsPerEvent: 3 // Safety limit default
      });

      // Kasih nafas buat Solana ngerapiin state
      await new Promise(resolve => setTimeout(resolve, 2500));

      // Refresh global context biar bot barunya langsung muncul di Dashboard
      await refresh();

      alert(`BERHASIL LAHIR! 🤖\nBot: ${agentName}\nID: ${autoGeneratedId}`);
      onClose?.();
    } catch (error: any) {
      console.error('Failed to create agent:', error);
      alert(`GAGAL TOTAL CU: ${error.message}`);
    } finally {
      setLoading(false);
    }
  }, [agentName, settings, createAgent, refresh, onClose]);

  return (
    <NeoCard className="p-8 bg-white border-4 border-black shadow-[12px_12px_0_0_#000000]">
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-6"
      >
        {/* Header Section */}
        <div className="border-b-4 border-black pb-4 flex justify-between items-center">
          <h3 className="font-display font-black text-3xl uppercase tracking-tighter italic">
            Birthing Bot
          </h3>
          <div className="bg-[#00FF41] border-2 border-black px-3 py-1 font-mono text-xs font-bold animate-pulse">
            SYSTEM ONLINE
          </div>
        </div>

        <div className="space-y-6 font-mono">
          {/* Bot Name Input */}
          <NeoInput
            label="AGENT NICKNAME"
            placeholder="e.g. Si Joki Garis Keras"
            value={agentName}
            onChange={(e) => setAgentName(e.target.value)}
          />

          {/* Budget Grid */}
          <div className="grid grid-cols-2 gap-6">
            <NeoInput
              label="MAX PER TICKET (SOL)"
              type="number"
              step="0.01"
              value={settings.maxBudgetPerTicket}
              onChange={(e) => setSettings({ ...settings, maxBudgetPerTicket: Number(e.target.value) })}
            />
            <NeoInput
              label="TOTAL BUDGET (SOL)"
              type="number"
              step="0.1"
              value={settings.totalBudget}
              onChange={(e) => setSettings({ ...settings, totalBudget: Number(e.target.value) })}
            />
          </div>

          {/* Automation Control */}
          <div className="bg-neutral-100 border-4 border-black p-4 space-y-4">
            <div className="flex justify-between items-center">
              <span className="font-black text-sm uppercase">Auto-Sniping Mode</span>
              <NeoToggle
                checked={settings.autoPurchaseEnabled}
                onChange={(checked) => setSettings({ ...settings, autoPurchaseEnabled: checked })}
              />
            </div>
            
            {settings.autoPurchaseEnabled && (
              <div className="pt-2 border-t-2 border-black/10">
                <NeoInput
                  label="THRESHOLD (%)"
                  type="number"
                  min="1"
                  max="100"
                  value={settings.autoPurchaseThreshold}
                  onChange={(e) => setSettings({ ...settings, autoPurchaseThreshold: Number(e.target.value) })}
                />
                <p className="text-[10px] text-neutral-500 mt-2 italic leading-tight">
                  *Bot hanya akan membeli tiket jika harga berada di bawah persentase budget ini.
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Action Button */}
        <NeoButton
          variant="primary"
          className="w-full py-6 text-2xl shadow-[6px_6px_0_0_#000000]"
          onClick={handleSave}
          disabled={loading || !agentName.trim()}
        >
          {loading ? (
            <span className="flex items-center gap-3">
              <div className="w-5 h-5 border-4 border-black border-t-transparent rounded-full animate-spin" />
              SEQUENCING DNA...
            </span>
          ) : (
            "CONFIRM & LAUNCH 🚀"
          )}
        </NeoButton>

        <p className="font-mono text-[10px] text-center text-neutral-400 uppercase tracking-widest">
          Pulse Protocol v1.0 // Fully Autonomous Agent
        </p>
      </motion.div>
    </NeoCard>
  );
};